### PR TITLE
Support long QPIGS responses of the PIP6048MT

### PR DESCRIPTION
**Pull request by WallK**
Added an example of PIP6048MT QPIGS response
Made PIPSOLAR_READ_BUFFER_LENGTH bigger to fit this response

### CODE REVIEW

**Review by syssi — APPROVED** [review]
LGTM!

**Comment by lucasimons** [comment]
image

I have the 4024MT version this is my log, i can t use the 2424mse1 branch i have this error

[logs_easun_logs.txt](https://github.com/syssi/esphome-pipsolar/files/10573778/logs_easun_logs.txt)

**Comment by syssi** [comment]
@lucasimons Please a `select` entity to your configuration or use the example configuration from this feature branch. It contains entities which must be part of the configuration at the moment and aren't optional. If this doesn't work out of the box please perform a clean build:

```
esphome clean yourconfig.yaml
esphome run yourconfig.yaml
```

**Comment by lucasimons** [comment]
Thanks now it works fine

**Pull request merged**
